### ISSUE TITLE
Crontab not working.

### ISSUE THREAD

**Issue by aouicher** [PaulReekers/scrum-burndown-tool#1]
Hi,

After add you line (as in documentation) in the crontab, it seems that it's not working. We need to access to each board to update.
for information, we noticed that the update should be process at 7AM. And we have any error if we try to execute the cron command on terminal.
Please let me know.
Regards.

**Comment by PaulReekers** [comment]
What is the error? Are you using it with Jira or standalone?

**Comment by aouicher** [comment]
There is no error and we use Jira Standalone

**Comment by PaulReekers** [comment]
You need to change the your .env file file to log errors.
APP_DEBUG=true
APP_LOG_LEVEL=debug

**Comment by aouicher** [comment]
ok. I just changed these params. Back to you asap

**Comment by PaulReekers** [comment]
Will close this issue, because of no response.
